In [1]:
import jax

In [3]:
import os 

os.environ["JAX_PLATFORMS"] = "cpu"

In [10]:
A = jax.numpy.asarray([[2800.5, -193.78], [-3500.2, 1780.3]], dtype=jax.numpy.float32)

In [11]:
A

Array([[ 2800.5 ,  -193.78],
       [-3500.2 ,  1780.3 ]], dtype=float32)

In [13]:
scale = jax.numpy.max( jax.numpy.abs(A) )

In [16]:
(A / scale).round(3)

Array([[ 0.8  , -0.055],
       [-1.   ,  0.509]], dtype=float32)

In [17]:
(A / scale * 127).round(3)

Array([[ 101.61201,   -7.031  ],
       [-127.00001,   64.596  ]], dtype=float32)

In [18]:
jax.numpy.asarray(A / scale * 127, dtype=jax.numpy.int8)

Array([[ 101,   -7],
       [-127,   64]], dtype=int8)